Readme.md
examples/con.rs
examples/fd.rs
examples/server.rs
examples/sig.rs
src/client_conn.rs
src/lib.rs
src/marshal.rs
src/message.rs

I started removing unwraps. 
Also removed the extern crate mentions, it's no longer necessary since rust 2018 except I think sometimes in `build.rs` files.
And exposed the most important types (the ones used in the examples) so one can, but does not have to, explicitly specify the modules.

start replacing unwraps

---

src/signature.rs

I was wondering whether rustbus didn't handle Boolean type.
e.g. 
`$ dbus-send --type=method_call --dest=my.test.iface / my.test.iface boolean:true
`
gave to me UnmarshalError(InvalidSignature)
This pr just adds Boolean type to parser

Add missing Boolean signature to parser

---

src/message.rs

It seems like there is a typo in marshaling Boolean type signature

fix boolean signature typo

---

src/wire/marshal_base.rs
src/wire/marshal_container.rs

Before this change, DBus would reject some variant containing messages produced by this library if the null-byte cause things to be shifted when marshalling downstream types.

Null-terminate signature string when marshalling variants

---

src/message.rs
src/wire/marshal_base.rs

Rust's `String` is allowed to contain any valid UTF-8 including U+0000 (null byte). The DBus spec doesn't allow for U+0000.

Check for null bytes within String when marshalling

---

src/message.rs

Since `make_error_response` is a part of DynamicHeader already, `make_response` should also be added.

Added make_response method to DynamicHeader

---

src/message.rs
src/message_builder.rs
src/wire/unmarshal.rs

One of things I've found to be missing when working with the new `MarshalledMessage` struct is a better way to get parameters out of received messages.
Generally I find that when receiving messages on DBus, you know the exact types that you expect to receive. This lends itself to  a convenient pattern that I hope to introduce
```rust
// if you expect a message to containt 2 params of type String and bool
let (p1, p2): (String, bool) = marshalled_msg1.unmarshal_params2()?;
// if you expect a message to contain 3 params of type u8, u16, u32
let (p1, p2, p3) : (u8, u16, u32) = marshalled_msg2.unmarshal_params3()?;
```
I haven't tested or debugged this at all yet, because I want to see if this would be a good addition first.

Add get2(), get3(), ... as helper functions to MessageBodyParser

---

src/message_builder.rs

An empty body is still a valid body so I think there shouldn't be a panic when creating a `MessageBodyParser` from an empty body. If a body is unexpectedly empty, the users of the crate can handle that error when using the get functions.

No longer panic in MessageBodyParser::new() on empty sig

---

src/message_builder.rs

Currently, padding is added when marshaling variants before pushing the signature string. This results in a bad alignment of the variant's signature. 
This pad_to_align can be can also be removed (rather than moved down) because it is duplicative. According to the [docs](https://docs.rs/rustbus/0.6.0/rustbus/wire/marshal/traits/trait.Marshal.html#implementing-for-your-own-structs) Marshal impls should do their own alignment:
>1. .... If your type is marshalled as a primitive type you still need to align to that types alignment.

Fix variant marshalling

---

src/lib.rs
src/message_builder.rs
src/params/validation.rs
src/wire/marshal/traits.rs
src/wire/unmarshal/traits.rs
src/wire/validate_raw.rs

This struct implements the `Unmarshal` trait, and act as intermediate that allows for the unmarshalling of variants. The struct has a `get()` method that similiar to `MessageBodyParser::get()` to retrieve the inner value.
Would there be any interest in adding something like this the crate? Currently there isn't a way to deconstruct a variant using the `Unmarshal` trait as far as I know, this is an attempt to remedy that, and this a solution from another crate I've been working on.
This PR still has some work to do. I haven't tested it beyond some simple examples, it still needs unit testing, and it needs documentation, but I would rather do after I know that this is worth inclusion.

Add Variant struct to unmarshal variants

---

src/client_conn.rs

Primarily intended to allow polling with other file descriptors. This can provide a massive performance benefit to applications that wish to maintain a low latency when responding to requests while also reducing system calls.
`RpcConn::conn` was added as an immutable complement to `RpcConn::conn_mut` to make `AsRawFd` more flexible.

Add AsRawFd impl to Conn

---

example_keywallet/src/bin/client/main.rs
example_keywallet/src/bin/service/main.rs
rustbus/benches/marshal_benchmark.rs
rustbus/examples/conn.rs
rustbus/examples/dispatch.rs
rustbus/examples/fd.rs
rustbus/examples/sig.rs
rustbus/examples/user_defined_types.rs
rustbus/src/connection/dispatch_conn.rs
rustbus/src/connection/ll_conn.rs
rustbus/src/connection/rpc_conn.rs
rustbus/src/lib.rs
rustbus/src/peer/peer_handling.rs
rustbus/src/tests/mod.rs
rustbus/src/wire/marshal/mod.rs
rustbus/src/wire/marshal/traits.rs
rustbus/src/wire/unixfd.rs
rustbus/src/wire/unmarshal/traits.rs

Merge the result of splitting the low level conn into  two types, one for sending and one for receiving.
This is done to make it possible for the dispatch_conn to provide a `Arc<Mutex<SendConn>>` which in turn allows for sending signals asynchronously to receiving new method calls.

Split conn

---

example_keywallet/src/bin/client/main.rs
example_keywallet/src/bin/service/collection_interface.rs
example_keywallet/src/bin/service/item_interface.rs
example_keywallet/src/bin/service/main.rs
example_keywallet/src/bin/service/service.rs
rustbus/Cargo.toml
rustbus/benches/marshal_benchmark.rs
rustbus/examples/conn.rs
rustbus/examples/dispatch.rs
rustbus/examples/fd.rs
rustbus/examples/server.rs
rustbus/examples/sig.rs
rustbus/examples/user_defined_types.rs
rustbus/src/connection/dispatch_conn.rs
rustbus/src/connection/ll_conn.rs
rustbus/src/connection/rpc_conn.rs
rustbus/src/lib.rs
rustbus/src/message_builder.rs
rustbus/src/params/validation.rs
rustbus/src/peer/peer_handling.rs
rustbus/src/tests/dbus_send.rs
rustbus/src/tests/fdpassing.rs
rustbus/src/tests/mod.rs
rustbus/src/wire/marshal/mod.rs
rustbus/src/wire/unixfd.rs

This branch implements primitives for handling short writes on the connection by providing means to resume sending through a `SendMessageContext`.

Short writes

---

rustbus/src/message_builder.rs

Useful if you used the `from_parts` method to build a marshalled message and want to check if it valid.

Add MarshalledMessageBody::validate()

---

rustbus/src/signature.rs
rustbus/src/wire/validate_raw.rs

When validating integer types and doubles, any bit-pattern is valid. When validating an array of just these types, you can skip validating each element individually.
This improves the runtime of validating arrays of these always-valid-types from O(n) to O(1).
Also a bug was fixed in validating arrays that allowed for the last element to overflow the array.

Optimize validate_marshalled_container when unmarshalling simple types.

---

example_keywallet/src/bin/client/main.rs
example_keywallet/src/bin/service/main.rs
rustbus/examples/deriving.rs
rustbus/examples/dispatch.rs
rustbus/examples/fd.rs
rustbus/examples/sig.rs
rustbus/examples/systemd_example.rs
rustbus/examples/user_defined_types.rs
rustbus/src/bin/create_corpus.rs
rustbus/src/connection/dispatch_conn.rs
rustbus/src/lib.rs
rustbus/src/message_builder.rs
rustbus/src/standard_messages.rs
rustbus/src/tests/fdpassing.rs
rustbus/src/tests/mod.rs
rustbus/src/wire/unmarshal/traits.rs
rustbus_derive_test/src/lib.rs

In my experience when building messages, you are almost always working with string slices when filling out the fields of a message because interface names, method names, and often destinations tend to be well defined ahead of time. 
The creates a common pattern where you write something like this using `String::into()`/`to_string()`/`to_owned()` for the vast majority of calls:
```rust
let mut msg = rustbus::message_builder::MessageBuilder::new()
.call("SearchItems".into())
.on("/org/freedesktop/secrets".into())
.with_interface("org.freedesktop.Secret.Service".into())
.at("io.killingspark.secrets".into())
.build();
let mut sig = MessageBuilder::new()
.signal(
"io.killing.spark".into(),
"TestSignal".into(),
"/io/killing/spark".into(),
)
```
This pattern exists all through out the crate's …

Make MessageBuilder methods generic

---

rustbus/src/message_builder.rs
rustbus/src/wire/unixfd.rs
rustbus/src/wire/unmarshal/iter.rs
rustbus/src/wire/unmarshal/traits.rs
rustbus/src/wire/variant_macros.rs
rustbus_derive/src/lib.rs

First, the rustbus references within the macros where changed to use `$crate` instead. This allows the macro to be used in context where the rustbus crate isn't in scope (primarily if re-exporting).
Second, the `dbus_variant_var!` accepts types rather than paths. This allows for the users to directly use reference types in the macro without having to do an extra type def.

Improvements to variant macros

---

rustbus/src/message_builder.rs
rustbus/src/signature.rs
rustbus/src/wire/marshal/traits.rs
rustbus/src/wire/unmarshal/mod.rs
rustbus/src/wire/variant_macros.rs

I've been working on an async version of this crate, and have been working on performances optimizations for it. One of the slowest types to marshal/unmarshal was variants. This is unfortunate because variants are used a lot in DBus.
The expense is largely because getting the signature string is very expensive. It involves creating `signature::Type` which can be expensive if it is a container and it involves allocating a `String`. 
Often the signature string is static and could be gotten with a lot less effort sort of like how `Signature::alignment` can get the alignment faster that using `signature::Type::alignment`
This proposes a `Signature::sig_str` which takes a `Cow<str>` and stores/appends a signature into it.
By providing a default implementation it shouldn't interfere with …

Add Signature::sig_str and Marshal::marshal_as_variant

---

rustbus/src/params/validation.rs
rustbus/src/wire/marshal/traits.rs
rustbus/src/wire/unmarshal/traits.rs
rustbus/src/wire/util.rs

1. Previously some of the params::validations methods used an unecessary `Vec` to perform their validation. This eliminates them.
2. Add some inline statements for very simple functions to help with external crates marshaling performance.
3. Simplify various marshaling functions. `marshal_base_param` is too complex to be efficiently inline which is important for marshaling loops like when using arrays.

Misc performance improvements

---

rustbus/src/lib.rs
rustbus/src/wire/marshal/traits.rs
rustbus/src/wire/unmarshal/traits.rs
rustbus/src/wire/util.rs

Similar to a validation change I made earlier, this change can make unmarshalling and marshalling certain integer types a lot faster by skipping the looping unmarshal/marshal and just memcopying or creating direct references. 
I don't like this method of introducing this optimization, but Rust hasn't added specialization yet which would enable this with more traditional traits by allowing for overlapping trait implementations. I feel this PR's way is worth it until Rust's type system improves enough that it can be done more cleanly. 
It also introduces a `Cow` unmarshal that can take advantage of this if unmarshaling a native-endian message or automatically switch to a `Vec` if it is non-native.

Create a `Signature::valid_slice` for improved marshalling performance

---

rustbus/src/connection.rs

DBus 1.14.4 makes a behavior change (
https://raw.githubusercontent.com/freedesktop/dbus/dbus-1.14/NEWS ) to some users' session bus paths, which can result in a DBUS_SESSION_BUS_ADDRESS of the format:
unix:path=/tmp/dbus-28xxxxxxxx,guid=xxxxxxxxx8198ffd295e9c5a5637c20bf
Particularly, the DBus session keys are appended to the end of the filesystem path. This commit fixes rustbus' session bus path detection algorithm for systems impacted.
(I found this [after a dbus update broke mpris-notifier](https://github.com/l1na-forever/mpris-notifier/issues/2) :crying_cat_face: )

Fix session bus path detection for dbus 1.14.4+

---

rustbus/src/params/types.rs
rustbus/src/tests/verify_marshalling.rs

My usecase: I was implementing `org.freedesktop.DBus.Properties.GetAll` which returns `a{sv}`. In Rust's types that would be `HashMap<&str, Variant>`, but I couldn't use it because of the missing impls. `Container::make_dict_ref("s", "v", ...)` works, but not nearly as ergonomic and forces to go through `push_old_param` instead of the new `push_param`.
I did not implement `Unmarshal`, because I didn't need it yet. Let me know it I should add it too for completeness.

implement Signature and Marshal for params::Variant

---

rustbus/src/params/conversion.rs
rustbus/src/wire/marshal/traits/base.rs
rustbus/src/wire/unmarshal/traits/base.rs

I did not touch `Base::Double` and left it holding `u64` to avoid breaking changes.
I did not implement `From<&'a f64> for Base<'a>` because it would require a transmute from `&'a f64` to `&'a u64`, which may be safe, but...
1. Is there any value in having the `...Ref` variants for scalar variants? Obviously it is needed for strings, but what is the point of holding a shared reference to a number? Please correct me if there are usecases.
2. If `...Ref`s are useful, then changing `Double` and `DoubleRef` to hold `f64` is a better solution. That's a breaking change, but the README says it's fine :)
Closes #86

implement (Un)marshall and Signature for f64

---

rustbus/src/auth.rs
rustbus/src/connection/ll_conn.rs
rustbus/src/wire/marshal/traits/container.rs
rustbus/src/wire/unmarshal/traits/container.rs
rustbus/src/wire/util.rs

`ptr::cast<T>` is supposed to be a more "safe" way to cast pointers. `extend_from_slice` may be more performant than `extend`.

avoid raw pointre casts using "as"; perfer extend_from_slice

---

rustbus/Cargo.toml
rustbus/src/connection/ll_conn.rs
rustbus/src/tests/fdpassing.rs

And deprecate `RecvConn::can_read_from_source` as discussed earlier.

update nix to 0.28

---

rustbus/Cargo.toml
rustbus/benches/marshal_benchmark.rs
rustbus/fuzz/fuzz_targets/fuzz_unmarshal.rs
rustbus/src/bin/fuzz_artifact.rs
rustbus/src/connection/ll_conn.rs
rustbus/src/message_builder.rs
rustbus/src/params/types.rs
rustbus/src/tests.rs
rustbus/src/tests/fdpassing.rs
rustbus/src/wire.rs
rustbus/src/wire/marshal.rs
rustbus/src/wire/marshal/traits/container.rs
rustbus/src/wire/unmarshal.rs
rustbus/src/wire/unmarshal/iter.rs
rustbus/src/wire/unmarshal/param/base.rs
rustbus/src/wire/unmarshal/param/container.rs
rustbus/src/wire/unmarshal/traits.rs
rustbus/src/wire/unmarshal/traits/base.rs
rustbus/src/wire/unmarshal/traits/container.rs
rustbus/src/wire/unmarshal_context.rs
rustbus/src/wire/util.rs
rustbus/src/wire/validate_raw.rs
rustbus/src/wire/variant_macros.rs
rustbus/src/wire/wrapper_types/unixfd.rs
rustbus_derive/Cargo.toml
rustbus_derive/src/structs.rs
rustbus_derive/src/variants.rs
rustbus_derive_test/Cargo.toml

Parsing was updating the offset of the UnmarshalContext all over the place. This PR cleans this up by making offset and buf private and adding read_xxx functions for the primitives to the UnmarshalContext, which 
* aligns itself correctly
* parses the primitive
* updates its offset
This is a big refactor and the testing seems like it could use a good cleanup itself.

Refactor parsing

---

rustbus/src/auth.rs

auth: send ScmCreds on FreeBSD and Dragonfly

---

rustbus/benches/marshal_benchmark.rs
rustbus/src/bin/create_corpus.rs
rustbus/src/bin/perf_test.rs
rustbus/src/connection/ll_conn.rs
rustbus/src/connection/rpc_conn.rs
rustbus/src/message_builder.rs
rustbus/src/tests.rs
rustbus/src/wire.rs
rustbus/src/wire/errors.rs
rustbus/src/wire/marshal.rs
rustbus/src/wire/unmarshal.rs

From the spec:
> 2nd UINT32 - The serial of this message, used as a cookie by the
> sender to identify the reply corresponding to this request. This must
> not be zero.

Enforce that serials are not zero

---

example_keywallet/src/bin/service/main.rs
rustbus/src/message_builder.rs
rustbus/src/wire/marshal.rs

Fix error replies, improve header marshalling, marshal all header fields

---

rustbus_derive/src/structs.rs
rustbus_derive/src/variants.rs

Unqualified references to `Result` can cause problems when the user shadows the `Result` type in their own crate.
For example:
```rust
type Result<T> = std::result::Result<T, rustbus::connection::Error>;
#[derive(Debug, Clone, rustbus::Signature, rustbus::Unmarshal)]
struct SystemdUnitDescription {
name: String,
description: String,
load_state: String,
active_state: String,
sub_state: String,
followed: String,
path: ObjectPath<String>,
job_id: u32,
job_type: String,
job_path: ObjectPath<String>,
}
```
```
error[E0107]: type alias takes 1 generic argument but 2 generic arguments were supplied
--> src/systemd.rs:97:44
|
97 | #[derive(Debug, Clone, rustbus::Signature, rustbus::Unmarshal)]
|                                            ^^^^^^^^^^^^^^^^^^
| …
```

qualify path to Result type in the derive macro quotes
